### ISSUE TITLE
Restart Bit

### ISSUE THREAD

**Issue by aretana** [Yingzhen-ietf/BGP-QUIC#1]
Why do we need a Restart bit in the Capability?    I'm assuming that all the other capabilities still apply, so Graceful Restart would handle a restart.    ??

**Comment by Yingzhen-ietf** [comment]
Hi,

So you’re recovered from IETF week. :)

Yes, all other capabilities still apply. The R bit here is to indicate this is a reset session (in case only one direction in QUIC bidrectional streams got reset) , not sure we really need it (We can put some requirement about bidirectional implementation, for example, if one direction is reset, the other MUST be reset also), but we can reserve a flag field. We need to decide whether we include the AFI/SAFI in this capability, or use the one in MP extension capability.

Thanks,
Yingzhen

**Comment by aretana** [comment]
Yes, if the session is reset in one direction is MUST be reset in the other.  This is important so we don't have to change the general behavior of BGP.

I don't think we need the AFI/SAFI in the capability.  I'm about to post something (as a new issue) describing a couple more flags.
