### ISSUE TITLE
Multi streams for one AFI/SAFI

### ISSUE THREAD

**Issue by Yingzhen-ietf** [Yingzhen-ietf/BGP-QUIC#12]
As Jeff suggested, use IPv4 unicast as an example, 10% prefixes may cover 80% of traffic, multiple steams may help to prioritize route convergence.

**Comment by aretana** [comment]
-02: "A function channel for a specific Network layer protocol MUST NOT be created if one already exists."

IOW, only one stream per AFI/SAFI is allowed.
