### ISSUE TITLE
Will BGP over QUIC ever run out of bytes?

### ISSUE THREAD

**Issue by Yingzhen-ietf** [Yingzhen-ietf/BGP-QUIC#15]
Streams and connections in QUIC can each carry a maximum of 2^62-1 bytes in each direction due to encoding limitations on stream offsets and connection flow control limits.  In case this limit is reached, a new connection needs to be established. 
BoQ is a long lasting connection, will it run out of bytes count?

**Comment by jhaas-pfrc** [comment]
2^62 - 1 is roughly 4.6 * 10^18
Let's pick an example of something as busy as the RIPE RIS servers.  Looking at https://data.ris.ripe.net/rrc00/2023.12/ which covers the month of December 2023, the updates files are on average less than 10M in zipped form.  BGP compresses very well, so if we presume the 4-5M expands to 2x to 10M that can help us with a heuristic.

There are 8928 5 minute intervals in a 31 day month.

At 10MB for all 5 minute samples in that month, this gives us 8.9*10^10.

Presuming multiplicative expansion for a year (times 12), we're still significantly under 10^18.

I think we're good.

Even if we're not good, closing a stream and opening a new one would bring us back up.  If BGP over QUIC sessions are long-lived enough to require coordination of this, we're far more successful than I'd expect.

**Comment by Yingzhen-ietf** [comment]
LOL. I totally agree with you. We'd be happy to see this problem.

Yingzhen
