### ISSUE TITLE
0-RTT

### ISSUE THREAD

**Issue by aretana** [Yingzhen-ietf/BGP-QUIC#9]
Is there any advantage to using 0-RTT when opening a QUIC connection?

In general, the exchange of the initial OPEN message could be accelerated -- is this an advantage?

**Comment by aretana** [comment]
There's no advantage for initial session establishment, but maybe for connection resumption (GR) ???

**Comment by jhaas-pfrc** [comment]
"However, 0-RTT provides no protection against replay attacks; see [Section 9.2](https://www.rfc-editor.org/rfc/rfc9001#section-9.2) of [[QUIC-TLS](https://www.rfc-editor.org/rfc/rfc9000.html#QUIC-TLS)]."

0-RTT might be helpful to permit session resumption happen slightly faster, but given the point is to resume a session with good security properties, the text above might bother our security folk.

I don't think there's a reason to push 0-RTT cases for BGP.
